No log message supplied

diff --git a/docker/z5.zenika-chrome/rootfs/entrypoint b/docker/z5.zenika-chrome/rootfs/entrypoint
--- a/docker/z5.zenika-chrome/rootfs/entrypoint
+++ b/docker/z5.zenika-chrome/rootfs/entrypoint
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+echo "$0: I am $USER" >&2
+
 if [ -d /home/chrome/.ca ]
 then
     [ -d /home/chrome/.ca/nssdb ]            || { echo "Missing CA dir: nssdb"; exit 10; }
@@ -7,7 +9,7 @@ then
     # set -x
     # ls -al /home/chrome/.ca >&2
     # ls -al /home/chrome/.ca/nssdb >&2
-    mkdir -p /home/chrome/.pki/nssdb || exit 12
+    mkdir -p /home/chrome/.pki/nssdb || { echo "ERROR trying to mkdir /home/chrome/.pki/nssdb: $?"; exit 12; }
     cp -f /home/chrome/.ca/nssdb/* /home/chrome/.pki/nssdb || exit 13
     sed -i 's#sql:.\+.pki/nssdb#sql:/home/chrome/.pki/nssdb#' /home/chrome/.pki/nssdb/pkcs11.txt || exit 14
     # cat /home/chrome/.pki/nssdb/pkcs11.txt >&2
