No log message supplied

diff --git a/sh/cleanup b/sh/cleanup
--- a/sh/cleanup
+++ b/sh/cleanup
@@ -17,22 +17,34 @@ cleanup._import () {
 cleanup._import "$@"
 
 # Modified from script found here: https://blog.dhampir.no/content/fixing-shmget-failed-no-space-left-on-device
-cleanup.shared_memory () {
+cleanup._shared_memory () {
+    local user; user="$1"
+
     # shellcheck disable=SC2162
     while read key id owner nattch; do
         if [[ -z $key ]] || [[ -z $id ]] || [[ -z $owner ]]; then
-            errcho "Ignoring invalid line from ipcs: [${key} ${id} ${owner} ${nattch}]"
+            echo "Ignoring invalid line from ipcs: [${key} ${id} ${owner} ${nattch}]" >&2
             continue
         fi
 
         local output
         if output=$(ipcrm shm "$id" 2>&1); then
-            gerrcho "Cleanup shared memory: removed [${key} ${id} ${owner} ${nattch}]"
+            echo "Cleanup shared memory: removed [${key} ${id} ${owner} ${nattch}]" >&2
         else
-            errcho "Failed to delete line from ipcs: [${key} ${id} ${owner} ${nattch}]"
-            errcho "Output given: [${output}]"
+            echo "Failed to delete line from ipcs: [${key} ${id} ${owner} ${nattch}]" >&2
+            echo "Output given: [${output}]" >&2
         fi
-    done < <(ipcs -m | grep "^0x" | awk '{print $1, $2, $3, $6}' | grep " 0$" | grep "$USER")
+    done < <(ipcs -m | grep "^0x" | awk '{print $1, $2, $3, $6}' | grep " 0$" | grep "$user")
+}
+
+cleanup.shared_memory () {
+    if test.i_can_sudo_root
+    then
+        local func; func=$(declare -f cleanup._shared_memory)
+        sudo bash -c "$func; cleanup._shared_memory root"
+    fi
+
+    cleanup._shared_memory "$USER"
 }
 
 # https://riptutorial.com/bash/example/2398/accumulate-a-list-of-trap-work-to-run-at-exit-
