No log message supplied

diff --git a/sh/importer b/sh/importer
--- a/sh/importer
+++ b/sh/importer
@@ -48,13 +48,21 @@ fi
 # don't put this inside functions, it'll get it wrong (see link)
 _z5stdlibshdir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 
-stdlib.self_update () {(
+declare -xA Z5_STDLIB_SEARCHDIRS
+
+Z5_STDLIB_SEARCHDIRS["$_z5stdlibshdir"]=1
+
+add.searchdir () {
+    Z5_STDLIB_SEARCHDIRS["$1"]=1
+}
+
+stdlib.self_update () (
     cd "$_z5stdlibshdir"/..
     # git is installed; the current user owns this file; stdlibdir is in a git repo
     if which git > /dev/null && [[ -O ${BASH_SOURCE[0]} ]] && git rev-parse 2> /dev/null ; then
         git pull > /dev/null
     fi
-)}
+)
 
 debug_stdlib () {
     [[ $DEBUG_STDLIB -ne 1 ]] && return 0
@@ -71,6 +79,7 @@ debug_stdlib () {
 # import somelib
 import () {
     local lib; lib="$1"; shift
+    # note for the confused: debug_stdlib always returns true
     [[ -n ${Imported[$lib]+x} ]] && [[ ${Imported[$lib]} -eq 1 ]] && debug_stdlib "Already imported $lib" && return 0
     reimport "$lib" "$@"
 }
@@ -79,16 +88,21 @@ reimport () {
     local lib; lib="$1"; shift
     debug_stdlib "Importing $lib"
 
-    if [[ -f "$_z5stdlibshdir/$lib" ]]; then
-        # shellcheck disable=SC1090
-        source "$_z5stdlibshdir/$lib" "$@" # || { echo "ERROR: importing $lib ($?)"; return "$?"; }
-        Imported[$lib]=1
-        debug_stdlib "Imported $lib"
-        return 0
-    else
-        echo "ERROR: Library '$lib' not found in $_z5stdlibshdir" >&2
-        return 1
-    fi
+    local -a searchdirs; searchdirs=("${!Z5_STDLIB_SEARCHDIRS[@]}")
+
+    for searchdir in "${searchdirs[@]}"
+    do
+        if [[ -f "$searchdir/$lib" ]]; then
+            # shellcheck disable=SC1090
+            source "$searchdir/$lib" "$@" # || { echo "ERROR: importing $lib ($?)"; return "$?"; }
+            Imported[$lib]=1
+            debug_stdlib "Imported $lib"
+            return 0
+        fi
+    done
+
+    echo "ERROR: Library '$lib' not found in ${searchdirs[*]}" >&2
+    return 1
 }
 
 if [[ $DEBUG_STDLIB -eq 1 ]]; then
