Cloud init via CDROM/iso working

diff --git a/sh/importer b/sh/importer
--- a/sh/importer
+++ b/sh/importer
@@ -8,6 +8,8 @@ if [[ -n ${1:-} && $1 == strict ]]; then
     set -o noclobber
 fi
 
+declare -A Imported
+
 # set DEBUG_STDLIB unless it was already exported by caller
 test_debug=${DEBUG_STDLIB:-}
 if [[ -z $test_debug ]]; then
@@ -15,38 +17,47 @@ if [[ -z $test_debug ]]; then
 fi
 
 # https://unix.stackexchange.com/questions/4650/determining-path-to-sourced-shell-script
-
 # don't put this inside functions, it'll get it wrong (see link)
 _z5stdlibshdir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-_z5stdlibdir="$(dirname "$_z5stdlibshdir")"
+# _z5stdlibdir="$(dirname "$_z5stdlibshdir")"
 
-# TODO: use a cache e.g. in ~/.z5.stdlibrc.d to only do this 1x per hour
-_stdlib_self_update () {(
-    cd "$_z5stdlibdir"
-    # git is installed; the current user owns this file; stdlibdir is in a git repo
-    if which git > /dev/null && [[ -O ${BASH_SOURCE[0]} ]] && git rev-parse 2> /dev/null ; then
-        git pull > /dev/null
+# # TODO: use a cache e.g. in ~/.z5.stdlibrc.d to only do this 1x per hour
+# _stdlib_self_update () {(
+#     cd "$_z5stdlibdir"
+#     # git is installed; the current user owns this file; stdlibdir is in a git repo
+#     if which git > /dev/null && [[ -O ${BASH_SOURCE[0]} ]] && git rev-parse 2> /dev/null ; then
+#         git pull > /dev/null
+#     fi
+# )}
+
+# _stdlib_self_update
+
+debug_stdlib () {
+    [[ $DEBUG_STDLIB -ne 1 ]] && return 0
+
+    local debug_msg="[${BASH_SOURCE[1]}::${FUNCNAME[1]}()]: $*"
+
+    if [[ -n ${Imported[errcho]+x} ]] && [[ ${Imported[errcho]} -eq 1 ]]; then
+        yerrcho "$debug_msg"
+    else
+        echo "$debug_msg" >&2
     fi
-)}
-
-_stdlib_self_update
-
-declare -A imported
+}
 
 # import somelib
 import () {
     local lib; lib="$1"
     shift
-
-    # declare -A imported
+    debug_stdlib "Import $lib"
 
     if [[ -f "$_z5stdlibshdir/$lib" ]]; then
-        [[ -n ${imported[$lib]+x} ]] && [[ ${imported[$lib]} -eq 1 ]] && return 0
+        [[ -n ${Imported[$lib]+x} ]] && [[ ${Imported[$lib]} -eq 1 ]] && debug_stdlib "... already imported $lib" && return 0
 
+        debug_stdlib "Importing $lib"
         # shellcheck disable=SC1090
-        source "$_z5stdlibshdir/$lib" "$@"
-        imported[$lib]=1
-        [[ $DEBUG_STDLIB -eq 1 ]] && echo "STDLIB imported: $lib" >&2
+        source "$_z5stdlibshdir/$lib" "$@" # || { echo "ERROR: importing $lib ($?)"; return "$?"; }
+        Imported[$lib]=1
+        debug_stdlib "Imported $lib"
         return 0
     else
         echo "ERROR: Library '$lib' not found in $_z5stdlibshdir" >&2
@@ -54,6 +65,9 @@ import () {
     fi
 }
 
-[[ $DEBUG_STDLIB -eq 1 ]] && { import errcho; import stacktrace; }
+if [[ $DEBUG_STDLIB -eq 1 ]]; then
+    import errcho
+    import stacktrace
+fi
 
-debug_stdlib () { [[ $DEBUG_STDLIB -eq 1 ]] && yerrcho "STDLIB::${BASH_SOURCE[1]}::${FUNCNAME[1]}: $*"; return 0; }
+
